openapi: 3.0.0
info:
  title: Todosense API Documentation
  description: API documentation for Todosense, a cloud-based Notes app.
  version: 1.0.0
servers:
  - url: /api/v1
    description: Development server

Certainly! Here is the merged `paths` key for both sets of paths:

paths:
  /auth/createuser:
    post:
      summary: Create a new user
      description: Endpoint to register a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuthResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      summary: User login
      description: Endpoint for user login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuthResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/getuser:
    post:
      summary: Get user details
      description: Endpoint to fetch details of the logged-in user.
      responses:
        '200':
          description: User data fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /notes/fetchallnotes:
    get:
      summary: Get all notes for logged-in user
      description: Returns all notes for the authenticated user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: All Notes Fetched Successfully
                notes:
                  - _id: "noteId"
                    title: "Note Title"
                    description: "Note Description"
                    tag: "Note Tag"
                    date: "2024-01-30T12:00:00.000Z"
                    user: "userId"

  /notes/addnote:
    post:
      summary: Add a new note for logged-in user
      description: Adds a new note for the authenticated user.
      requestBody:
        content:
          application/json:
            example:
              title: "New Note"
              description: "Note Description"
              tag: "Note Tag"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note added successfully
                note:
                  _id: "noteId"
                  title: "New Note"
                  description: "Note Description"
                  tag: "Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"

  /notes/updatenote/{id}:
    put:
      summary: Update an existing note for logged-in user
      description: Updates an existing note for the authenticated user.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Note ID
      requestBody:
        content:
          application/json:
            example:
              title: "Updated Note"
              description: "Updated Note Description"
              tag: "Updated Note Tag"
              date: "2024-01-30T12:00:00.000Z"
              isCompleted: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note Updated Successfully
                note:
                  _id: "noteId"
                  title: "Updated Note"
                  description: "Updated Note Description"
                  tag: "Updated Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"

  /notes/deletenote/{id}:
    delete:
      summary: Delete a note for logged-in user
      description: Deletes a note for the authenticated user.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Note ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note deleted Successfully
                note:
                  _id: "noteId"
                  title: "Deleted Note"
                  description: "Deleted Note Description"
                  tag: "Deleted Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"

  /notes/markasdone/{id}:
    patch:
      summary: Mark a note as read for logged-in user
      description: Marks a note as read for the authenticated user.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Note ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note marked as read successfully
                note:
                  _id: "noteId"
                  title: "Read Note"
                  description: "Read Note Description"
                  tag: "Read Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"

components:
  schemas:
    UserRegistration:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        cpassword:
          type: string
      required:
        - name
        - email
        - password
        - cpassword

    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    UserAuthResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        authToken:
          type: string
        data:
          type: object
          properties:
            user:
              type: object
              properties:
                id:
                  type: string

    UserDetailsResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        user:
          type: object
          properties:
            _id:
              type: string
            name:
              type: string
            email:
              type: string
  /notes/gettasks:
    get:
      summary: Get all notes for logged-in user
      description: Returns all notes for the authenticated user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: All Notes Fetched Successfully
                notes:
                  - _id: "noteId"
                    title: "Note Title"
                    description: "Note Description"
                    tag: "Note Tag"
                    date: "2024-01-30T12:00:00.000Z"
                    user: "userId"

  /notes/addtask:
    post:
      summary: Add a new note for logged-in user
      description: Adds a new note for the authenticated user.
      requestBody:
        content:
          application/json:
            example:
              title: "New Note"
              description: "Note Description"
              tag: "Note Tag"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note added successfully
                note:
                  _id: "noteId"
                  title: "New Note"
                  description: "Note Description"
                  tag: "Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"

  /notes/updatetask/{id}:
    put:
      summary: Update an existing note for logged-in user
      description: Updates an existing note for the authenticated user.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Note ID
      requestBody:
        content:
          application/json:
            example:
              title: "Updated Note"
              description: "Updated Note Description"
              tag: "Updated Note Tag"
              date: "2024-01-30T12:00:00.000Z"
              isCompleted: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note Updated Successfully
                note:
                  _id: "noteId"
                  title: "Updated Note"
                  description: "Updated Note Description"
                  tag: "Updated Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"

  /notes/deletetask/{id}:
    delete:
      summary: Delete a note for logged-in user
      description: Deletes a note for the authenticated user.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Note ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note deleted Successfully
                note:
                  _id: "noteId"
                  title: "Deleted Note"
                  description: "Deleted Note Description"
                  tag: "Deleted Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"

  /notes/markasdone/{id}:
    patch:
      summary: Mark a note as read for logged-in user
      description: Marks a note as read for the authenticated user.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Note ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Note marked as read successfully
                note:
                  _id: "noteId"
                  title: "Read Note"
                  description: "Read Note Description"
                  tag: "Read Note Tag"
                  date: "2024-01-30T12:00:00.000Z"
                  user: "userId"
